package com.bookstore.mapper;

import com.bookstore.domain.Address;
import com.bookstore.dto.request.AddressRequest;
import com.bookstore.dto.response.AddressResponse;
import org.mapstruct.*;
import org.mapstruct.ReportingPolicy;

/**
 * MapStruct mapper for {@link Address} entity ↔ address DTOs.
 *
 * <p>Note on boolean {@code isDefault}: Lombok {@code @Getter} generates {@code isDefault()}
 * as the accessor, so MapStruct sees the source property name as {@code "default"} (stripping
 * the leading {@code is}). The response DTO and entity both share this quirk.
 * Explicit cross-mappings wire the {@code "default"} source to the {@code "isDefault"} target
 * for builder-based creation, and vice versa where needed.
 * For {@code @MappingTarget} (setter-based update) the setter generated by Lombok is
 * {@code setDefault(boolean)}, so the target property name is {@code "default"}.
 */
/**
 * {@code unmappedTargetPolicy = IGNORE} suppresses warnings for {@code id} and
 * {@code createdAt} on builder-based mappings — those fields are inherited from
 * {@link com.bookstore.domain.BaseCreatedEntity} and cannot be set via the Lombok builder.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface AddressMapper {

    // ── Entity → Response ─────────────────────────────────────────────────────

    /** Map {@code address.isDefault()} (property "default") to response field {@code isDefault}. */
    @Mapping(target = "isDefault", source = "default")
    AddressResponse toResponse(Address address);

    // ── Request → Entity (create — builder target) ────────────────────────────

    @Mapping(target = "user",     ignore = true)
    @Mapping(target = "isDefault", source = "default")
    Address toEntity(AddressRequest request);

    // ── Request → Entity (update — @MappingTarget setter target) ─────────────

    @Mapping(target = "user",    ignore = true)
    @Mapping(target = "default", source = "default")
    void updateEntity(AddressRequest request, @MappingTarget Address address);
}
